on: push

jobs:
  test:
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
    runs-on: ${{ matrix.os }}
    steps:
      - if: matrix.os == 'macos-latest'
        run: brew install gawk
      - uses: actions/checkout@v2
      - id: run_add
        run: echo "::set-output name=result::$(./run.sh Add)"
      - run: exit 1
        if: ${{ steps.run_add.outputs.result }} != 6

