on: push

jobs:
  test:
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
    runs-on: ${{ matrix.os }}
    steps:
      - run: brew install gawk
        if: ${{ runner.os }} == "macos"
      - run: awk --version
      - run: echo ${{ runner.os }}
