on: push

jobs:
  test:
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
    runs-on: ${{ matrix.os }}
    steps:
      - if: matrix.os == 'racos-latest'
        run: brew install gawk
      - run: awk --version
      - run: echo ${{ runner.os }}
